### ISSUE TITLE
WIP: 1.0.0-beta task list

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#342]
## 主题系统

- [ ] 组件类的 CSS 统一采用BEM命名规则
- [x] 移除 animate.css，已内置部分 motion 效果，可满足大部分场景
- [x] 移除主题色
- [x] 增加主题在线编辑器
- [x] 移除实验性 `14px` 字体
- [x] 移除样式
    - [x] 移除 `.file-upload` 由 `nz-upload` 替代
    - [x] 移除 `.list-group` 由 `nz-list` 替代

### 常规

- [x] 重构命名规则 #333 
- [x] 移除对 `_HttpClient` 依赖 #330 
- [x] 移除所有 `forRoot()` 可配置项
- [x] 移除 `moment` 依赖，改用 `date-fns`

### abc

- ~移除 `AlainABCModule`~
- [ ] Chart
    - [x] 重构组件模块化
    - [ ] 新增测试用例
- [x] 重构 `simple-table` #281
    - [x] 支持 `buttons` 条件选择

### cache

- [x] 增加变更通知 `key` #242 

### theme

- [x] 增加国际化 `change` 通知属性 #329 、移除 `firstLoad`
- [x] 移除 `ColorsService`
- [x] 移除 `ThemesService`

## 脚手架

- [x] 同步 zorro 0.7.0 版本
- [x] 移除 `ng-zorro-antd-extra`
- [x] 移除 `ng-tree-antd`
- [ ] 增加多应用
- ~国际化替换 `i18next`~

## 其它

- [x] 改善 [ng-zorro snippets](https://marketplace.visualstudio.com/items?itemName=cipchk.ng-zorro-vscode)
- [x] 重构 [nz-schema-form](https://github.com/cipchk/nz-schema-form/issues/43) 并同步 `0.7.0`

**Comment by winpzs** [comment]
* 希望多点考虑按需引用，不要启动太大了。
* animate尽量少用。。。
