### ISSUE TITLE
TODO: improves performance plans

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#49]
- [x] remove third libraries except g2
- [x] remove invalid dependencies
- [x] priority using `ng-zorro-antd-extra` components
- [x] adjust style when `preserveWhitespaces: false`
- [x] theme style move to styles file
- [x] ng-alain chart for using g2
    - [x] chart-card
    - [x] mini-bar
    - [x] mini-area
    - [x] mini-progress
    - [x] bar
    - [x] pie
    - [x] timeline
    - [x] gauge
    - [x] tag-cloud
    - [x] water-wave
    - [x] radar
- [x] implement more Ant Design Pro pages
- [ ] support mock server
